### PR TITLE
FIGS Fixes

### PR DESCRIPTION
**Pull request by mepland**
- Added [SKompiler](https://github.com/konstantint/SKompiler) integration, which required the new `n_features_in_` member variable.
   - Note the demo FIGS model currently requires https://github.com/mepland/SKompiler/tree/fixes to run which fixes a bug in SKompiler. TLDR SKompiler was not letting trees run if they use less than all the available features, like the demo FIGS tree 0.
- Fixed bug in `n_features`
```
-    n_features = np.unique(features[np.where( 0 < features )]).size
+    n_features = np.unique(features[np.where( 0 <= features )]).size
```
- Improved markdown comments in `FIGS_viz_demo.ipynb`

### CODE REVIEW

**Comment by mepland** [comment]
Related `SKompiler` PR is here: https://github.com/konstantint/SKompiler/pull/14

**Comment by csinva** [comment]
This is awesome! I'll bump the version once Skompiler does to include the change :)

**Comment by mepland** [comment]
@csinva thanks! Skompiler bumped [their version](https://pypi.org/project/SKompiler/#history). After imodels is bumped I can make a new PR with the notebook cleaned up and those paths removed.

**Comment by csinva** [comment]
Ah sorry for the slowness on this, somehow missed the notification...

Just bumped the version!

**Pull request merged**
